### ISSUE TITLE
Make vhost more generic

### ISSUE THREAD

**Issue by damien-carcel** [akeneo/Dockerfiles#185]
## Problem

Right now, Apache vhost and nginx server blocks expect the PIM to be in `/home/docker/symfony`. This folder should have a more generic name, like `application`, or `app`.

Another problem are the server names: `symfony.local` and `symfony-behat.local`. `.local` does not work on MacOS X. This can be solve by changing it for `.dev`.

## Todo

- [x] Change all Apache vhosts and nginx servers:
    - [x] use `application.dev` for `carcel/nginx` and `carcel/apapche-php` images and place document root at `/home/docker/application`,
    - [x] use `akeneo.dev` for `carcel/akeneo` and `akeneo-behat.dev` for`carcel/akeneo-behat` images and place document root at `/home/docker/pim`.
- [x] Update the documentation

**Comment by jmleroux** [comment]
If it's really for Akeneo PIM, i do not understand why it's not in `/home/docker/pim` like what we use in our internal LXC servers.

**Comment by damien-carcel** [comment]
Because it is not only for Akeneo PIM. The `apache-php` and `fpm` images can be used for any PHP application.
